#config_version=5

show_player:
  mode_attract_started:
    attract_dmd_loop:
      loops: -1
      speed: 1

    attract_lights_level:
      loops: -1
      speed: 3

    attract_lights_PM5K:
      loops: -1
      speed: 3

    attract_lights_metal:
      loops: -1
      speed: 3

    attract_lights_xvalue:
      loops: -1
      speed: 3

    attract_lights_guitar:
      loops: -1
      speed: 3

    attract_lights_pops:
      loops: -1
      speed: 5

  mode_attract_stopped:
    attract_dmd_loop:
      action: stop

    attract_lights_level:
      action: stop

    attract_lights_PM5K:
      action: stop

    attract_lights_album:
      action: stop

    attract_lights_xvalue:
      action: stop

    attract_lights_guitar:
      action: stop

    attract_lights_pops:
      action: stop
