#config_version=5

mode:
  start_events: ball_starting
  priority: 125

counters:
  lb_METAL_complete_count:
    count_events: METAL_Targets_complete
    events_when_hit: METAL_Targets_done
    starting_count: 0
    direction: up
    persist_state: false

shots:
  METAL:
    switch: s_metal_target
    show_tokens:
      light: l_right_25K_target
   

shot_groups:
  METAL_Targets:
    shots: METAL
    reset_events: 
      METAL_Targets_complete: 1s

variable_player:

  METAL_Targets_done{count==1}:
    score: 100 * current_player.pf_multiplier|block

  METAL_Targets_done{count==2}:
    score: 200 * current_player.pf_multiplier|block

  METAL_Targets_done{count==3}:
    score: 300 * current_player.pf_multiplier|block

  METAL_Targets_done{count==4}:
    score: 400 * current_player.pf_multiplier|block

  METAL_Targets_done{count==5}:
    score: 1000 * current_player.pf_multiplier|block

  METAL_Targets_done{count>=6}:
    score: 50 * current_player.pf_multiplier|block


show_player:

  METAL_Targets_done{count==1}:
    Metal_M_On:
      show_tokens:
        lights: Metal_M

  METAL_Targets_done{count==2}:
    Metal_E_On:
      show_tokens:
        lights: Metal_M, Metal_E

  METAL_Targets_done{count==3}:
    Metal_T_On:
      show_tokens:
        lights: Metal_M, Metal_E, Metal_T

  METAL_Targets_done{count==4}:
    Metal_A_On:
      show_tokens:
        lights: Metal_M, Metal_E, Metal_T, Metal_A

  METAL_Targets_done{count==5}:
    Metal_L_On:
      show_tokens:
        lights: Metal_M, Metal_E, Metal_T, Metal_A, Metal_L

  METAL_Targets_done{count>=6}:
    flash:
      loops: -1
      speed: 10
      show_tokens:
        lights: l_metal_m, l_metal_e, l_metal_t, l_metal_a, l_metal_l