#config_version=5

mode:
  priority: 152
  start_events: HEAVY_Targets_done{count==6}, METAL_Targets_done{count==6}, ball_starting
  stop_events:
    balldevice_left_saucer_enter

event_player:
  mode_Light_Setlist_stopping: Setlist_Unlit
  mode_Light_Setlist_started: Setlist_Lit, cancel_Setlist_timer
  mode_Light_Setlist_3s_started: cancel_Setlist_timer

counters:
  initialize_setlist:
    count_events: mode_Light_Setlist_started
    events_when_complete: initialize_setlist
    count_complete_value: 1
    persist_state: true