#config_version=5


switches:
    s_left_flipper:
        number: 0 
        tags: left_flipper
    s_right_flipper:
        number: 71
        tags: right_flipper
    s_left_saucer:
        number: 1
        tags: 
    s_right_saucer:
        number: 2
        tags: 
    s_load_chamber:
        number: 3
        tags: 
    s_eject_chamber:
        number: 4
        tags: playfield_active, Bonus_Multiplier

    s_cabinet_left:
        number: 5
        tags: playfield_active

    s_credit:
        number: 6
        tags: start

    s_cabinet_right:
        number: 7
        tags: playfield_active

    s_outhole:
        number: 8
        tags: 
    s_coins_right:
        number: 9
        tags: playfield_active
    s_coins_left:
        number: 10
        tags: playfield_active
    s_coins_middle:
        number: 11
        tags: playfield_active

    s_left_return_lane:
        number: 12
        tags: playfield_active
    s_right_return_lane:
        number: 13
        tags: playfield_active
    s_slam:
        number: 14
        tags: playfield_active
    s_tilt:
        number: 15
        tags: playfield_active
    s_ramp_drop_target:
        number: 16
        tags: 
    s_left_bumper:
        number: 17
        tags:  jet
    s_middle_bumper:
        number: 18
        tags: jet
    s_right_bumper:
        number: 19
        tags: jet
    s_right_slingshot:
        number: 20
        tags: 
    s_left_slingshot:
        number: 21
        tags: 

    s_top_lane_R:
        number: 22
        tags: playfield_active, Skull_lanes

    s_top_lane_C:
        number: 23
        tags: playfield_active, Skull_lanes

    s_top_lane_L:
        number: 24
        tags: playfield_active, Skull_lanes

    s_left_outlane:
        number: 25
        tags: playfield_active

    s_right_outlane:
        number: 26
        tags: playfield_active

    s_top_25K_lane:
        number: 27
        tags: playfield_active

    s_top_50K_lane:
        number: 28
        tags: playfield_active

    s_left_rollover:
        number: 29
        tags: playfield_active

    s_right_rollover:
        number: 30
        tags: playfield_active

    s_left_25K_target:
        number: 31
        tags: playfield_active

    s_right_25K_target:
        number: 32
        tags: playfield_active

    s_center_target:
        number: 33
        tags: playfield_active

    s_metal_target:
        number: 34
        tags: playfield_active

    s_heavy_target:
        number: 35
        tags: playfield_active

    s_trough_5:
        number: 36
        tags: 

    s_trough_4:
        number: 37
        tags: 

    s_trough_3:
        number: 38
        tags: 

    s_trough_2:
        number: 39
        tags:

    s_trough_1:
        number: 40
        tags: 