#config_version=5

mode:
  start_events: ball_starting
  priority: 120

counters:
  lb_HEAVY_complete_count:
    count_events: HEAVY_Targets_complete
    events_when_hit: HEAVY_Targets_done
    starting_count: 0
    direction: up
    persist_state: false

shots:
  HEAVY:
    switch: s_heavy_target
    show_tokens:
      light: l_left_25K_target
   

shot_groups:
  HEAVY_Targets:
    shots: HEAVY
    reset_events: 
      HEAVY_Targets_complete: 1s

variable_player:

  HEAVY_Targets_done{count==1}:
    score: 100 * current_player.pf_multiplier|block

  HEAVY_Targets_done{count==2}:
    score: 200 * current_player.pf_multiplier|block

  HEAVY_Targets_done{count==3}:
    score: 300 * current_player.pf_multiplier|block

  HEAVY_Targets_done{count==4}:
    score: 400 * current_player.pf_multiplier|block

  HEAVY_Targets_done{count==5}:
    score: 1000 * current_player.pf_multiplier|block

  HEAVY_Targets_done{count>=6}:
    score: 50 * current_player.pf_multiplier|block


show_player:

  HEAVY_Targets_done{count==1}:
    Heavy_H_On:
      show_tokens:
        lights: Heavy_H

  HEAVY_Targets_done{count==2}:
    Heavy_E_On:
      show_tokens:
        lights: Heavy_H, Heavy_E

  HEAVY_Targets_done{count==3}:
    Heavy_A_On:
      show_tokens:
        lights: Heavy_H, Heavy_E, Heavy_A

  HEAVY_Targets_done{count==4}:
    Heavy_V_On:
      show_tokens:
        lights: Heavy_H, Heavy_E, Heavy_A, Heavy_V

  HEAVY_Targets_done{count==5}:
    Heavy_Y_On:
      show_tokens:
        lights: Heavy_H, Heavy_E, Heavy_A, Heavy_V, Heavy_Y

  HEAVY_Targets_done{count>=6}:
    flash:
      loops: -1
      speed: 10
      show_tokens:
        lights: l_heavy_h, l_heavy_e, l_heavy_a, l_heavy_v, l_heavy_y